package ang.jinhang.emotionregulator.emotionclassifier

class EmoticonConverter() {
    private val emoticonDict = mapOf(
        ":‑)" to "Happy",
        ":-))" to "Very Happy",
        ":-)))" to "Very very Happy",
        ":)" to "Happy",
        ":))" to "Very Happy",
        ":)))" to "Very very Happy",
        ":-]" to "Happy",
        ":]" to "Happy",
        ":-3" to "Happy",
        ":3" to "Happy",
        ":->" to "Happy",
        ":>" to "Happy",
        "8-)" to "Happy",
        ":o)" to "Happy",
        ":-}" to "Happy",
        ":}" to "Happy",
        ":-)" to "Happy",
        ":c)" to "Happy",
        ":^)" to "Happy",
        "=]" to "Happy",
        "=)" to "Happy",
        ":‑D" to "Laughing",
        ":D" to "Laughing",
        "8‑D" to "Laughing",
        "8D" to "Laughing",
        "X‑D" to "Laughing",
        "XD" to "Laughing",
        "=D" to "Laughing",
        "=3" to "Laughing",
        "B^D" to "Laughing",
        "C:" to "Big grin",
        "c:" to "Big grin",
        ":-))" to "Very happy",
        ":-(" to "Frown, sad, angry or pouting",
        ":‑(" to "Frown, sad, angry or pouting",
        ":(" to "Frown, sad, angry or pouting",
        ":‑c" to "Frown, sad, angry or pouting",
        ":c" to "Frown, sad, angry or pouting",
        ":‑<" to "Frown, sad, angry or pouting",
        ":<" to "Frown, sad, angry or pouting",
        ":‑[" to "Frown, sad, angry or pouting",
        ":[" to "Frown, sad, angry or pouting",
        ":-||" to "Frown, sad, angry or pouting",
        ">:[" to "Frown, sad, angry or pouting",
        ":{" to "Frown, sad, angry or pouting",
        ":@" to "Frown, sad, angry or pouting",
        ">:(" to "Frown, sad, angry or pouting",
        ";(" to "Frown, sad, angry or pouting",
        ":'‑(" to "Crying",
        ":'(" to "Crying",
        ":=(" to "Crying",
        ":'‑)" to "Tears of happiness",
        ":')" to "Tears of happiness",
        "D‑':" to "Horror",
        "D:<" to "Disgust",
        "D:" to "Sadness",
        "D8" to "Great dismay",
        "D;" to "Great dismay",
        "D=" to "Great dismay",
        "DX" to "Great dismay",
        ":‑O" to "Surprise",
        ":O" to "Surprise",
        ":‑o" to "Surprise",
        ":o" to "Surprise",
        ":-0" to "Shock",
        "8‑0" to "Yawn",
        ">:O" to "Yawn",
        ":-*" to "Kiss",
        ":*" to "Kiss",
        ":X" to "Kiss",
        ":x" to "Kiss",
        ";‑)" to "Wink or smirk",
        ";)" to "Wink or smirk",
        "*-)" to "Wink or smirk",
        "*)" to "Wink or smirk",
        ";‑]" to "Wink or smirk",
        ";]" to "Wink or smirk",
        ";^)" to "Wink or smirk",
        ";^" to "Wink or smirk",
        ":‑," to "Wink or smirk",
        ";D" to "Wink or smirk",
        ":‑P" to "cheeky, playful",
        ":P" to "cheeky, playful",
        "X‑P" to "cheeky, playful",
        "XP" to "cheeky, playful",
        "x‑p" to "cheeky, playful",
        "xp" to "cheeky, playful",
        ":‑Þ" to "cheeky, playful",
        ":Þ" to "cheeky, playful",
        ":b" to "cheeky, playful",
        "d:" to "cheeky, playful",
        "=p" to "cheeky, playful",
        ">:P" to "cheeky, playful",
        ":‑/" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ":/" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ":-[.]" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ">:[(\\)]" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ">:/" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ":[(\\)]" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        "=/" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        "=[(\\)]" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ":L" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        "=L" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ":S" to "Skeptical, annoyed, undecided, uneasy or hesitant",
        ":‑|" to "Straight face",
        ":|" to "Straight face",
        ":$" to "Embarrassed or blushing",
        "://)" to "Embarrassed or blushing",
        "://3" to "Embarrassed or blushing",
        ":‑x" to "Sealed lips or tongue-tied",
        ":x" to "Sealed lips or tongue-tied",
        ":‑#" to "Sealed lips or tongue-tied",
        ":#" to "Sealed lips or tongue-tied",
        ":‑&" to "Sealed lips or tongue-tied",
        ":&" to "Sealed lips or tongue-tied",
        "O:‑)" to "innocent",
        "O:)" to "innocent",
        "0:‑3" to "innocent",
        "0:3" to "innocent",
        "0:‑)" to "innocent",
        "0:)" to "innocent",
        ":‑b" to "cheeky, playful",
        "0;^)" to "innocent",
        ">:‑)" to "Evil or devilish",
        ">:)" to "Evil or devilish",
        "}:‑)" to "Evil or devilish",
        "}:)" to "Evil or devilish",
        "3:‑)" to "Evil or devilish",
        "3:)" to "Evil or devilish",
        ">;)" to "Evil or devilish",
        "|;‑)" to "Cool",
        "|‑O" to "Bored",
        ":‑J" to "Tongue-in-cheek",
        "#‑)" to "Party all night",
        "%‑)" to "Drunk or confused",
        "%)" to "Drunk or confused",
        ":-###.." to "Being sick",
        ":###.." to "Being sick",
        "<:‑|" to "Dumb",
        "(>_<)" to "Troubled",
        "(>_<)>" to "Troubled",
        "(';')" to "Baby",
        "(^^>``" to "Nervous or Embarrassed or Troubled or Shy or Sweat drop",
        "(^_^;)" to "Nervous or Embarrassed or Troubled or Shy or Sweat drop",
        "(-_-;)" to "Nervous or Embarrassed or Troubled or Shy or Sweat drop",
        "(~_~;) (・.・;)" to "Nervous or Embarrassed or Troubled or Shy or Sweat drop",
        "(-_-)zzz" to "Sleeping",
        "(^_-)" to "Wink",
        "((+_+))" to "Confused",
        "(+o+)" to "Confused",
        "(o|o)" to "Ultraman",
        "^_^" to "Joyful",
        "(^_^)/" to "Joyful",
        "(^O^)／" to "Joyful",
        "(^o^)／" to "Joyful",
        "(__)" to "respect, apology",
        "_(._.)_" to "respect, apology",
        "<(_ _)>" to "respect, apology",
        "<m(__)m>" to "respect, apology",
        "m(__)m" to "respect, apology",
        "m(_ _)m" to "respect, apology",
        "('_')" to "Sad or Crying",
        "(/_;)" to "Sad or Crying",
        "(T_T) (;_;)" to "Sad or Crying",
        "(;_;" to "Sad of Crying",
        "(;_:)" to "Sad or Crying",
        "(;O;)" to "Sad or Crying",
        "(:_;)" to "Sad or Crying",
        "(ToT)" to "Sad or Crying",
        ";_;" to "Sad or Crying",
        ";-;" to "Sad or Crying",
        ";n;" to "Sad or Crying",
        ";;" to "Sad or Crying",
        "Q.Q" to "Sad or Crying",
        "T.T" to "Sad or Crying",
        "QQ" to "Sad or Crying",
        "Q_Q" to "Sad or Crying",
        "(-.-)" to "Shame",
        "(-_-)" to "Shame",
        "(一一)" to "Shame",
        "(；一_一)" to "Shame",
        "(=_=)" to "Tired",
        "(=^·^=)" to "cat",
        "(=^··^=)" to "cat",
        "=_^= " to "cat",
        "(..)" to "Looking down",
        "(._.)" to "Looking down",
        "^m^" to "Giggling",
        "(・・?" to "Confusion",
        "(?_?)" to "Confusion",
        ">^_^<" to "Normal Laugh",
        "<^!^>" to "Normal Laugh",
        "^/^" to "Normal Laugh",
        "（*^_^*）" to "Normal Laugh",
        "(^<^) (^.^)" to "Normal Laugh",
        "(^^)" to "Normal Laugh",
        "(^.^)" to "Normal Laugh",
        "(^_^.)" to "Normal Laugh",
        "(^_^)" to "Normal Laugh",
        "(^^)" to "Normal Laugh",
        "(^J^)" to "Normal Laugh",
        "(*^.^*)" to "Normal Laugh",
        "(^—^）" to "Normal Laugh",
        "(#^.^#)" to "Normal Laugh",
        "（^—^）" to "Waving",
        "(;_;)/~~~" to "Waving",
        "(^.^)/~~~" to "Waving",
        "(-_-)/~~~ ($··)/~~~" to "Waving",
        "(T_T)/~~~" to "Waving",
        "(ToT)/~~~" to "Waving",
        "(*^0^*)" to "Excited",
        "(*_*)" to "Amazed",
        "(*_*;" to "Amazed",
        "(+_+) (@_@)" to "Amazed",
        "(*^^)v" to "Laughing,Cheerful",
        "(^_^)v" to "Laughing,Cheerful",
        "((d[-_-]b))" to "Headphones,Listening to music",
        "(-\"-)" to "Worried",
        "(ーー;)" to "Worried",
        "(^0_0^)" to "Eyeglasses",
        "(＾ｖ＾)" to "Happy",
        "(＾ｕ＾)" to "Happy",
        "(^)o(^)" to "Happy",
        "(^O^)" to "Happy",
        "(^o^)" to "Happy",
        ")^o^(" to "Happy",
        ":O o_O" to "Surprised",
        "o_0" to "Surprised",
        "o.O" to "Surprised",
        "(o.o)" to "Surprised",
        "oO" to "Surprised",
        "(*￣m￣)" to "Dissatisfied",
        "(‘A`)" to "Snubbed or Deflated",
        "<3" to "Love",
        "</3" to "Heartbroken"
    )

    fun convertString(input: String): String {
        var newString = ""

        var maxKeyLength = 0
        var chosenReplacement = ""
        var currentIndex = 0
        while (currentIndex < input.length) {
            for ((key, value) in emoticonDict) {
                if (input.indexOf(key) == currentIndex) {
                    if (key.length > maxKeyLength) {
                        maxKeyLength = key.length
                        chosenReplacement = value
                    }
                }
            }
            if (maxKeyLength > 0) {
                newString += chosenReplacement
                currentIndex += maxKeyLength
            } else {
                newString += input[currentIndex]
                currentIndex += 1
            }

            maxKeyLength = 0
        }

        return newString
    }
}